// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using library_system.Models;

#nullable disable

namespace library_system.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LibrarianMember", b =>
                {
                    b.Property<int>("LibrariansId")
                        .HasColumnType("int");

                    b.Property<int>("MembersId")
                        .HasColumnType("int");

                    b.HasKey("LibrariansId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("LibrarianMember");
                });

            modelBuilder.Entity("library_system.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bookname")
                        .HasColumnType("longtext");

                    b.Property<int>("Fine")
                        .HasColumnType("int");

                    b.Property<DateTime>("Issuedate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LibrarianId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("LibrarianId")
                        .IsUnique();

                    b.ToTable("Alert");
                });

            modelBuilder.Entity("library_system.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AuthorName")
                        .HasColumnType("longtext");

                    b.Property<string>("BookName")
                        .HasColumnType("longtext");

                    b.Property<int>("CatalogId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.ToTable("Book");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Book");
                });

            modelBuilder.Entity("library_system.Models.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AuthorName")
                        .HasColumnType("longtext");

                    b.Property<int>("NoOfCopies")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Catalog");
                });

            modelBuilder.Entity("library_system.Models.Librarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<int>("Mobileno")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Librarian");
                });

            modelBuilder.Entity("library_system.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Maddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Mname")
                        .HasColumnType("longtext");

                    b.Property<int>("Mno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Member");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Member");
                });

            modelBuilder.Entity("library_system.Models.FacultyMember", b =>
                {
                    b.HasBaseType("library_system.Models.Member");

                    b.Property<string>("FacultyColl")
                        .HasColumnType("longtext");

                    b.Property<string>("Fname")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("FacultyMember");
                });

            modelBuilder.Entity("library_system.Models.GeneralBook", b =>
                {
                    b.HasBaseType("library_system.Models.Book");

                    b.HasDiscriminator().HasValue("GeneralBook");
                });

            modelBuilder.Entity("library_system.Models.ReferenceBook", b =>
                {
                    b.HasBaseType("library_system.Models.Book");

                    b.HasDiscriminator().HasValue("ReferenceBook");
                });

            modelBuilder.Entity("library_system.Models.Student", b =>
                {
                    b.HasBaseType("library_system.Models.Member");

                    b.Property<string>("SName")
                        .HasColumnType("longtext");

                    b.Property<string>("StudentColl")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("LibrarianMember", b =>
                {
                    b.HasOne("library_system.Models.Librarian", null)
                        .WithMany()
                        .HasForeignKey("LibrariansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("library_system.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("library_system.Models.Alert", b =>
                {
                    b.HasOne("library_system.Models.Librarian", "Librarian")
                        .WithOne("Alert")
                        .HasForeignKey("library_system.Models.Alert", "LibrarianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Librarian");
                });

            modelBuilder.Entity("library_system.Models.Book", b =>
                {
                    b.HasOne("library_system.Models.Catalog", "Catalog")
                        .WithMany("Books")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("library_system.Models.Catalog", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("library_system.Models.Librarian", b =>
                {
                    b.Navigation("Alert");
                });
#pragma warning restore 612, 618
        }
    }
}
